
runtime: python27
threadsafe: true


handlers:

# Static website
- url: /
  static_files: build/default/index.html
  upload: build/default/index\.html
  secure: always
- url: /
  static_dir: build/default
  secure: always

libraries:
- name: endpoints
  version: 1.0
- name: pycrypto
  version: latest
